### ISSUE TITLE
[DOCS] Add links to Languages & Tools icons

### ISSUE THREAD

**Issue by vikasganiga05** [Sagar0-0/Sagar0-0#2]
Hi, my suggestion is to add a link to every icon on the Languages & Tools section to its corresponding websites.

For example : 

<a href="https://www.python.org/"><code><img height="40" width="40" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png"></code></a>

```html
<a href="https://www.python.org/"><code><img height="40" width="40" src="https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png"></code></a>
```

**Comment by Sagar0-0** [comment]
That's super cool🌟. If you want, you can create a pull request corresponding to this issue. Your contribution will be appreciated.💯💯

**Comment by vikasganiga05** [comment]
Yes, I like to work on this issue.

**Comment by Sagar0-0** [comment]
Ok, Let's get this started!🔥

**Comment by vikasganiga05** [comment]
**DONE** :+1:
